package com.tp_sd_1.service;

import com.tp_sd_1.client.ResultClient;
import com.tp_sd_1.stubs.medicamento.*;

import com.tp_sd_1.dao.MedicamentoDao;
import com.tp_sd_1.entities.Medicamento;
import io.grpc.ManagedChannel;
import io.grpc.ManagedChannelBuilder;
import io.grpc.Status;
import io.grpc.stub.StreamObserver;

import static io.grpc.stub.ServerCalls.asyncUnimplementedUnaryCall;

import java.util.List;
import java.util.NoSuchElementException;
import java.util.logging.Level;
import java.util.logging.Logger;


import com.tp_sd_1.stubs.medicamento.MedicamentoRequest;

public class MedicamentoServiceImpl extends MedicamentoServiceGrpc.MedicamentoServiceImplBase {
    // We need to have an instance of the dao class to work with the database
    private MedicamentoDao medicamentoDao = new MedicamentoDao();
    // Let's use a logger to log everything that we want
    private static final Logger logger = Logger.getLogger(MedicamentoServiceImpl.class.getName());

    // We have to override the getStudentInfo that was defined in the StudentService class
	// The StudentService class is an autogenerated class by the proto file
    // So, let's override the getStudentInfo method here.   
    
    
    @Override
    public void getMedicamentoInfo(MedicamentoRequest request, StreamObserver<MedicamentoResponse> responseObserver) {
        int id = request.getId();// the student ID should be passed with the request message

        try{
            Medicamento medicamento = medicamentoDao.findById(id); // Let's find the student information from the student table

            /*
                The getResults method will help us to fetch the results for the student from the result service.
                this method will call the result service through its client and bring back the result as a list of strings
             */
            List<String> resultResponse = getResults(id);

            // Once all the results are clear, we can build our response message
            MedicamentoResponse medicamentoResponse = MedicamentoResponse.newBuilder()
                    .setId(id)
                    .setCodigo(medicamento.getCodigo())
                    .setNombreComercial(medicamento.getNombreComercial())
                    .setNombreDroga(medicamento.getNombreDroga())
                    .build();

            /*
                gRPC works in an asynchronous manner, so if you have ever worked with asynchronous programming
                you would know what will happen with following two methods.
                with the onNext method we send the response, once the response is sent we use onCompleted()
            */
            responseObserver.onNext(medicamentoResponse);
            responseObserver.onCompleted();
        }catch (NoSuchElementException e){
            logger.log(Level.SEVERE, "NO STUDENT FOUND WITH THE STUDENT ID :- "+id);

            // If some error occurs we sent an error with the following status which is not_found
            responseObserver.onError(Status.NOT_FOUND.asRuntimeException());
        }
    }

    public List<String> getResults(int id){

        // To connect with the ResultClient we need something called a channel
        // This is how you create a channel,
        ManagedChannel channel = ManagedChannelBuilder.forTarget("localhost:9090")
                .usePlaintext()
                .build();

        ResultClient resultClient = new ResultClient(channel);

        return resultClient.getResults(id);
    }
}