# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: tipoMedicamento.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
from google.protobuf import wrappers_pb2 as google_dot_protobuf_dot_wrappers__pb2
from google.protobuf import any_pb2 as google_dot_protobuf_dot_any__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='tipoMedicamento.proto',
  package='com.medicamentos_management.stubs.tipoMedicamento',
  syntax='proto3',
  serialized_options=b'P\001',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x15tipoMedicamento.proto\x12\x31\x63om.medicamentos_management.stubs.tipoMedicamento\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1egoogle/protobuf/wrappers.proto\x1a\x19google/protobuf/any.proto\"\x1b\n\rIdBajaRequest\x12\n\n\x02id\x18\x01 \x01(\x05\"4\n\x16TipoMedicamentoRequest\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0e\n\x06nombre\x18\x02 \x01(\t\"5\n\x17TipoMedicamentoResponse\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0e\n\x06nombre\x18\x02 \x01(\t2\x99\x04\n\x16TipoMedicamentoService\x12\xae\x01\n\x13\x61ltaTipoMedicamento\x12I.com.medicamentos_management.stubs.tipoMedicamento.TipoMedicamentoRequest\x1aJ.com.medicamentos_management.stubs.tipoMedicamento.TipoMedicamentoResponse\"\x00\x12\x9b\x01\n\x13\x62\x61jaTipoMedicamento\x12@.com.medicamentos_management.stubs.tipoMedicamento.IdBajaRequest\x1a@.com.medicamentos_management.stubs.tipoMedicamento.IdBajaRequest\"\x00\x12\xaf\x01\n\x16getTipoMedicamentoInfo\x12I.com.medicamentos_management.stubs.tipoMedicamento.TipoMedicamentoRequest\x1aJ.com.medicamentos_management.stubs.tipoMedicamento.TipoMedicamentoResponseB\x02P\x01\x62\x06proto3'
  ,
  dependencies=[google_dot_protobuf_dot_empty__pb2.DESCRIPTOR,google_dot_protobuf_dot_wrappers__pb2.DESCRIPTOR,google_dot_protobuf_dot_any__pb2.DESCRIPTOR,])




_IDBAJAREQUEST = _descriptor.Descriptor(
  name='IdBajaRequest',
  full_name='com.medicamentos_management.stubs.tipoMedicamento.IdBajaRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='com.medicamentos_management.stubs.tipoMedicamento.IdBajaRequest.id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=164,
  serialized_end=191,
)


_TIPOMEDICAMENTOREQUEST = _descriptor.Descriptor(
  name='TipoMedicamentoRequest',
  full_name='com.medicamentos_management.stubs.tipoMedicamento.TipoMedicamentoRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='com.medicamentos_management.stubs.tipoMedicamento.TipoMedicamentoRequest.id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='nombre', full_name='com.medicamentos_management.stubs.tipoMedicamento.TipoMedicamentoRequest.nombre', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=193,
  serialized_end=245,
)


_TIPOMEDICAMENTORESPONSE = _descriptor.Descriptor(
  name='TipoMedicamentoResponse',
  full_name='com.medicamentos_management.stubs.tipoMedicamento.TipoMedicamentoResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='com.medicamentos_management.stubs.tipoMedicamento.TipoMedicamentoResponse.id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='nombre', full_name='com.medicamentos_management.stubs.tipoMedicamento.TipoMedicamentoResponse.nombre', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=247,
  serialized_end=300,
)

DESCRIPTOR.message_types_by_name['IdBajaRequest'] = _IDBAJAREQUEST
DESCRIPTOR.message_types_by_name['TipoMedicamentoRequest'] = _TIPOMEDICAMENTOREQUEST
DESCRIPTOR.message_types_by_name['TipoMedicamentoResponse'] = _TIPOMEDICAMENTORESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

IdBajaRequest = _reflection.GeneratedProtocolMessageType('IdBajaRequest', (_message.Message,), {
  'DESCRIPTOR' : _IDBAJAREQUEST,
  '__module__' : 'tipoMedicamento_pb2'
  # @@protoc_insertion_point(class_scope:com.medicamentos_management.stubs.tipoMedicamento.IdBajaRequest)
  })
_sym_db.RegisterMessage(IdBajaRequest)

TipoMedicamentoRequest = _reflection.GeneratedProtocolMessageType('TipoMedicamentoRequest', (_message.Message,), {
  'DESCRIPTOR' : _TIPOMEDICAMENTOREQUEST,
  '__module__' : 'tipoMedicamento_pb2'
  # @@protoc_insertion_point(class_scope:com.medicamentos_management.stubs.tipoMedicamento.TipoMedicamentoRequest)
  })
_sym_db.RegisterMessage(TipoMedicamentoRequest)

TipoMedicamentoResponse = _reflection.GeneratedProtocolMessageType('TipoMedicamentoResponse', (_message.Message,), {
  'DESCRIPTOR' : _TIPOMEDICAMENTORESPONSE,
  '__module__' : 'tipoMedicamento_pb2'
  # @@protoc_insertion_point(class_scope:com.medicamentos_management.stubs.tipoMedicamento.TipoMedicamentoResponse)
  })
_sym_db.RegisterMessage(TipoMedicamentoResponse)


DESCRIPTOR._options = None

_TIPOMEDICAMENTOSERVICE = _descriptor.ServiceDescriptor(
  name='TipoMedicamentoService',
  full_name='com.medicamentos_management.stubs.tipoMedicamento.TipoMedicamentoService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=303,
  serialized_end=840,
  methods=[
  _descriptor.MethodDescriptor(
    name='altaTipoMedicamento',
    full_name='com.medicamentos_management.stubs.tipoMedicamento.TipoMedicamentoService.altaTipoMedicamento',
    index=0,
    containing_service=None,
    input_type=_TIPOMEDICAMENTOREQUEST,
    output_type=_TIPOMEDICAMENTORESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='bajaTipoMedicamento',
    full_name='com.medicamentos_management.stubs.tipoMedicamento.TipoMedicamentoService.bajaTipoMedicamento',
    index=1,
    containing_service=None,
    input_type=_IDBAJAREQUEST,
    output_type=_IDBAJAREQUEST,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='getTipoMedicamentoInfo',
    full_name='com.medicamentos_management.stubs.tipoMedicamento.TipoMedicamentoService.getTipoMedicamentoInfo',
    index=2,
    containing_service=None,
    input_type=_TIPOMEDICAMENTOREQUEST,
    output_type=_TIPOMEDICAMENTORESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_TIPOMEDICAMENTOSERVICE)

DESCRIPTOR.services_by_name['TipoMedicamentoService'] = _TIPOMEDICAMENTOSERVICE

# @@protoc_insertion_point(module_scope)
