# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: medicamento.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
from google.protobuf import wrappers_pb2 as google_dot_protobuf_dot_wrappers__pb2
from google.protobuf import any_pb2 as google_dot_protobuf_dot_any__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='medicamento.proto',
  package='',
  syntax='proto3',
  serialized_options=b'P\001',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x11medicamento.proto\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1egoogle/protobuf/wrappers.proto\x1a\x19google/protobuf/any.proto\"e\n\x0fMedicamentoList\x12 \n\nresultList\x18\x01 \x03(\x0b\x32\x0c.Medicamento\x12\x30\n\x0bresultCount\x18\x02 \x01(\x0b\x32\x1b.google.protobuf.Int32Value\"-\n\x0fTipoMedicamento\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0e\n\x06nombre\x18\x02 \x01(\t\"w\n\x0bMedicamento\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0e\n\x06\x63odigo\x18\x02 \x01(\t\x12\x17\n\x0fnombreComercial\x18\x03 \x01(\t\x12\x13\n\x0bnombreDroga\x18\x04 \x01(\t\x12\x1e\n\x04tipo\x18\x05 \x01(\x0b\x32\x10.TipoMedicamento\"E\n\nPagination\x12\x0c\n\x04page\x18\x01 \x01(\x05\x12\x10\n\x08pageSize\x18\x02 \x01(\x05\x12\x17\n\x06search\x18\x03 \x01(\x0b\x32\x07.Search\"B\n\x06Search\x12$\n\x06\x66ilter\x18\x01 \x01(\x0b\x32\x14.google.protobuf.Any\x12\x12\n\njsonFilter\x18\x02 \x01(\t2\xa3\x01\n\x16TipoMedicamentoService\x12;\n\x13\x61ltaTipoMedicamento\x12\x10.TipoMedicamento\x1a\x10.TipoMedicamento\"\x00\x12L\n\x13\x62\x61jaTipoMedicamento\x12\x1b.google.protobuf.Int32Value\x1a\x16.google.protobuf.Empty\"\x00\x32\xca\x01\n\x12MedicamentoService\x12/\n\x0f\x61ltaMedicamento\x12\x0c.Medicamento\x1a\x0c.Medicamento\"\x00\x12<\n\x19listarMedicamentosAerosol\x12\x0b.Pagination\x1a\x10.MedicamentoList\"\x00\x12\x45\n\"listarMedicamentosNombreComercialA\x12\x0b.Pagination\x1a\x10.MedicamentoList\"\x00\x42\x02P\x01\x62\x06proto3'
  ,
  dependencies=[google_dot_protobuf_dot_empty__pb2.DESCRIPTOR,google_dot_protobuf_dot_wrappers__pb2.DESCRIPTOR,google_dot_protobuf_dot_any__pb2.DESCRIPTOR,])




_MEDICAMENTOLIST = _descriptor.Descriptor(
  name='MedicamentoList',
  full_name='MedicamentoList',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='resultList', full_name='MedicamentoList.resultList', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='resultCount', full_name='MedicamentoList.resultCount', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=109,
  serialized_end=210,
)


_TIPOMEDICAMENTO = _descriptor.Descriptor(
  name='TipoMedicamento',
  full_name='TipoMedicamento',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='TipoMedicamento.id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='nombre', full_name='TipoMedicamento.nombre', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=212,
  serialized_end=257,
)


_MEDICAMENTO = _descriptor.Descriptor(
  name='Medicamento',
  full_name='Medicamento',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='Medicamento.id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='codigo', full_name='Medicamento.codigo', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='nombreComercial', full_name='Medicamento.nombreComercial', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='nombreDroga', full_name='Medicamento.nombreDroga', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='tipo', full_name='Medicamento.tipo', index=4,
      number=5, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=259,
  serialized_end=378,
)


_PAGINATION = _descriptor.Descriptor(
  name='Pagination',
  full_name='Pagination',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='page', full_name='Pagination.page', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='pageSize', full_name='Pagination.pageSize', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='search', full_name='Pagination.search', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=380,
  serialized_end=449,
)


_SEARCH = _descriptor.Descriptor(
  name='Search',
  full_name='Search',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='filter', full_name='Search.filter', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='jsonFilter', full_name='Search.jsonFilter', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=451,
  serialized_end=517,
)

_MEDICAMENTOLIST.fields_by_name['resultList'].message_type = _MEDICAMENTO
_MEDICAMENTOLIST.fields_by_name['resultCount'].message_type = google_dot_protobuf_dot_wrappers__pb2._INT32VALUE
_MEDICAMENTO.fields_by_name['tipo'].message_type = _TIPOMEDICAMENTO
_PAGINATION.fields_by_name['search'].message_type = _SEARCH
_SEARCH.fields_by_name['filter'].message_type = google_dot_protobuf_dot_any__pb2._ANY
DESCRIPTOR.message_types_by_name['MedicamentoList'] = _MEDICAMENTOLIST
DESCRIPTOR.message_types_by_name['TipoMedicamento'] = _TIPOMEDICAMENTO
DESCRIPTOR.message_types_by_name['Medicamento'] = _MEDICAMENTO
DESCRIPTOR.message_types_by_name['Pagination'] = _PAGINATION
DESCRIPTOR.message_types_by_name['Search'] = _SEARCH
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

MedicamentoList = _reflection.GeneratedProtocolMessageType('MedicamentoList', (_message.Message,), {
  'DESCRIPTOR' : _MEDICAMENTOLIST,
  '__module__' : 'medicamento_pb2'
  # @@protoc_insertion_point(class_scope:MedicamentoList)
  })
_sym_db.RegisterMessage(MedicamentoList)

TipoMedicamento = _reflection.GeneratedProtocolMessageType('TipoMedicamento', (_message.Message,), {
  'DESCRIPTOR' : _TIPOMEDICAMENTO,
  '__module__' : 'medicamento_pb2'
  # @@protoc_insertion_point(class_scope:TipoMedicamento)
  })
_sym_db.RegisterMessage(TipoMedicamento)

Medicamento = _reflection.GeneratedProtocolMessageType('Medicamento', (_message.Message,), {
  'DESCRIPTOR' : _MEDICAMENTO,
  '__module__' : 'medicamento_pb2'
  # @@protoc_insertion_point(class_scope:Medicamento)
  })
_sym_db.RegisterMessage(Medicamento)

Pagination = _reflection.GeneratedProtocolMessageType('Pagination', (_message.Message,), {
  'DESCRIPTOR' : _PAGINATION,
  '__module__' : 'medicamento_pb2'
  # @@protoc_insertion_point(class_scope:Pagination)
  })
_sym_db.RegisterMessage(Pagination)

Search = _reflection.GeneratedProtocolMessageType('Search', (_message.Message,), {
  'DESCRIPTOR' : _SEARCH,
  '__module__' : 'medicamento_pb2'
  # @@protoc_insertion_point(class_scope:Search)
  })
_sym_db.RegisterMessage(Search)


DESCRIPTOR._options = None

_TIPOMEDICAMENTOSERVICE = _descriptor.ServiceDescriptor(
  name='TipoMedicamentoService',
  full_name='TipoMedicamentoService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=520,
  serialized_end=683,
  methods=[
  _descriptor.MethodDescriptor(
    name='altaTipoMedicamento',
    full_name='TipoMedicamentoService.altaTipoMedicamento',
    index=0,
    containing_service=None,
    input_type=_TIPOMEDICAMENTO,
    output_type=_TIPOMEDICAMENTO,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='bajaTipoMedicamento',
    full_name='TipoMedicamentoService.bajaTipoMedicamento',
    index=1,
    containing_service=None,
    input_type=google_dot_protobuf_dot_wrappers__pb2._INT32VALUE,
    output_type=google_dot_protobuf_dot_empty__pb2._EMPTY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_TIPOMEDICAMENTOSERVICE)

DESCRIPTOR.services_by_name['TipoMedicamentoService'] = _TIPOMEDICAMENTOSERVICE


_MEDICAMENTOSERVICE = _descriptor.ServiceDescriptor(
  name='MedicamentoService',
  full_name='MedicamentoService',
  file=DESCRIPTOR,
  index=1,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=686,
  serialized_end=888,
  methods=[
  _descriptor.MethodDescriptor(
    name='altaMedicamento',
    full_name='MedicamentoService.altaMedicamento',
    index=0,
    containing_service=None,
    input_type=_MEDICAMENTO,
    output_type=_MEDICAMENTO,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='listarMedicamentosAerosol',
    full_name='MedicamentoService.listarMedicamentosAerosol',
    index=1,
    containing_service=None,
    input_type=_PAGINATION,
    output_type=_MEDICAMENTOLIST,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='listarMedicamentosNombreComercialA',
    full_name='MedicamentoService.listarMedicamentosNombreComercialA',
    index=2,
    containing_service=None,
    input_type=_PAGINATION,
    output_type=_MEDICAMENTOLIST,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_MEDICAMENTOSERVICE)

DESCRIPTOR.services_by_name['MedicamentoService'] = _MEDICAMENTOSERVICE

# @@protoc_insertion_point(module_scope)
