# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
from google.protobuf import wrappers_pb2 as google_dot_protobuf_dot_wrappers__pb2

from . import medicamento_pb2 as medicamento__pb2

class TipoMedicamentoServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.altaTipoMedicamento = channel.unary_unary(
                '/TipoMedicamentoService/altaTipoMedicamento',
                request_serializer=medicamento__pb2.TipoMedicamento.SerializeToString,
                response_deserializer=medicamento__pb2.TipoMedicamento.FromString,
                )
        self.bajaTipoMedicamento = channel.unary_unary(
                '/TipoMedicamentoService/bajaTipoMedicamento',
                request_serializer=google_dot_protobuf_dot_wrappers__pb2.Int32Value.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                )


class TipoMedicamentoServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def altaTipoMedicamento(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def bajaTipoMedicamento(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_TipoMedicamentoServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'altaTipoMedicamento': grpc.unary_unary_rpc_method_handler(
                    servicer.altaTipoMedicamento,
                    request_deserializer=medicamento__pb2.TipoMedicamento.FromString,
                    response_serializer=medicamento__pb2.TipoMedicamento.SerializeToString,
            ),
            'bajaTipoMedicamento': grpc.unary_unary_rpc_method_handler(
                    servicer.bajaTipoMedicamento,
                    request_deserializer=google_dot_protobuf_dot_wrappers__pb2.Int32Value.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'TipoMedicamentoService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class TipoMedicamentoService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def altaTipoMedicamento(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/TipoMedicamentoService/altaTipoMedicamento',
            medicamento__pb2.TipoMedicamento.SerializeToString,
            medicamento__pb2.TipoMedicamento.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def bajaTipoMedicamento(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/TipoMedicamentoService/bajaTipoMedicamento',
            google_dot_protobuf_dot_wrappers__pb2.Int32Value.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)


class MedicamentoServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.altaMedicamento = channel.unary_unary(
                '/MedicamentoService/altaMedicamento',
                request_serializer=medicamento__pb2.Medicamento.SerializeToString,
                response_deserializer=medicamento__pb2.Medicamento.FromString,
                )
        self.listarMedicamentosAerosol = channel.unary_unary(
                '/MedicamentoService/listarMedicamentosAerosol',
                request_serializer=medicamento__pb2.Pagination.SerializeToString,
                response_deserializer=medicamento__pb2.MedicamentoList.FromString,
                )
        self.listarMedicamentosNombreComercialA = channel.unary_unary(
                '/MedicamentoService/listarMedicamentosNombreComercialA',
                request_serializer=medicamento__pb2.Pagination.SerializeToString,
                response_deserializer=medicamento__pb2.MedicamentoList.FromString,
                )


class MedicamentoServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def altaMedicamento(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def listarMedicamentosAerosol(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def listarMedicamentosNombreComercialA(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_MedicamentoServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'altaMedicamento': grpc.unary_unary_rpc_method_handler(
                    servicer.altaMedicamento,
                    request_deserializer=medicamento__pb2.Medicamento.FromString,
                    response_serializer=medicamento__pb2.Medicamento.SerializeToString,
            ),
            'listarMedicamentosAerosol': grpc.unary_unary_rpc_method_handler(
                    servicer.listarMedicamentosAerosol,
                    request_deserializer=medicamento__pb2.Pagination.FromString,
                    response_serializer=medicamento__pb2.MedicamentoList.SerializeToString,
            ),
            'listarMedicamentosNombreComercialA': grpc.unary_unary_rpc_method_handler(
                    servicer.listarMedicamentosNombreComercialA,
                    request_deserializer=medicamento__pb2.Pagination.FromString,
                    response_serializer=medicamento__pb2.MedicamentoList.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'MedicamentoService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class MedicamentoService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def altaMedicamento(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/MedicamentoService/altaMedicamento',
            medicamento__pb2.Medicamento.SerializeToString,
            medicamento__pb2.Medicamento.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def listarMedicamentosAerosol(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/MedicamentoService/listarMedicamentosAerosol',
            medicamento__pb2.Pagination.SerializeToString,
            medicamento__pb2.MedicamentoList.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def listarMedicamentosNombreComercialA(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/MedicamentoService/listarMedicamentosNombreComercialA',
            medicamento__pb2.Pagination.SerializeToString,
            medicamento__pb2.MedicamentoList.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
