spring:
  datasource:
    url: jdbc:mysql://localhost:3306/tp_sd_1?serverTimezone=UTC
    username: root
    password: 2771999
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      dialect: org.hibernate.dialect.MySQL5Dialect
  thymeleaf:
    cache: false