// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: medicamento.proto

package com.tp_sd_1.stubs.medicamento;

public interface MedicamentoResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.tp_sd_1.stubs.medicamento.MedicamentoResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 id = 1;</code>
   */
  int getId();

  /**
   * <code>string codigo = 2;</code>
   */
  java.lang.String getCodigo();
  /**
   * <code>string codigo = 2;</code>
   */
  com.google.protobuf.ByteString
      getCodigoBytes();

  /**
   * <code>string nombreComercial = 3;</code>
   */
  java.lang.String getNombreComercial();
  /**
   * <code>string nombreComercial = 3;</code>
   */
  com.google.protobuf.ByteString
      getNombreComercialBytes();

  /**
   * <code>string nombreDroga = 4;</code>
   */
  java.lang.String getNombreDroga();
  /**
   * <code>string nombreDroga = 4;</code>
   */
  com.google.protobuf.ByteString
      getNombreDrogaBytes();

  /**
   * <code>.com.tp_sd_1.stubs.medicamento.TipoMedicamento tipo = 5;</code>
   */
  boolean hasTipo();
  /**
   * <code>.com.tp_sd_1.stubs.medicamento.TipoMedicamento tipo = 5;</code>
   */
  com.tp_sd_1.stubs.medicamento.TipoMedicamento getTipo();
  /**
   * <code>.com.tp_sd_1.stubs.medicamento.TipoMedicamento tipo = 5;</code>
   */
  com.tp_sd_1.stubs.medicamento.TipoMedicamentoOrBuilder getTipoOrBuilder();
}
