// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: medicamento.proto

package com.tp_sd_1.stubs.medicamento;

public interface MedicamentoListOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.tp_sd_1.stubs.medicamento.MedicamentoList)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .com.tp_sd_1.stubs.medicamento.Medicamento resultList = 1;</code>
   */
  java.util.List<com.tp_sd_1.stubs.medicamento.Medicamento> 
      getResultListList();
  /**
   * <code>repeated .com.tp_sd_1.stubs.medicamento.Medicamento resultList = 1;</code>
   */
  com.tp_sd_1.stubs.medicamento.Medicamento getResultList(int index);
  /**
   * <code>repeated .com.tp_sd_1.stubs.medicamento.Medicamento resultList = 1;</code>
   */
  int getResultListCount();
  /**
   * <code>repeated .com.tp_sd_1.stubs.medicamento.Medicamento resultList = 1;</code>
   */
  java.util.List<? extends com.tp_sd_1.stubs.medicamento.MedicamentoOrBuilder> 
      getResultListOrBuilderList();
  /**
   * <code>repeated .com.tp_sd_1.stubs.medicamento.Medicamento resultList = 1;</code>
   */
  com.tp_sd_1.stubs.medicamento.MedicamentoOrBuilder getResultListOrBuilder(
      int index);

  /**
   * <code>.google.protobuf.Int32Value resultCount = 2;</code>
   */
  boolean hasResultCount();
  /**
   * <code>.google.protobuf.Int32Value resultCount = 2;</code>
   */
  com.google.protobuf.Int32Value getResultCount();
  /**
   * <code>.google.protobuf.Int32Value resultCount = 2;</code>
   */
  com.google.protobuf.Int32ValueOrBuilder getResultCountOrBuilder();
}
