// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: medicamento.proto

package com.tp_sd_1.stubs.medicamento;

/**
 * Protobuf type {@code com.tp_sd_1.stubs.medicamento.MedicamentoList}
 */
public  final class MedicamentoList extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:com.tp_sd_1.stubs.medicamento.MedicamentoList)
    MedicamentoListOrBuilder {
private static final long serialVersionUID = 0L;
  // Use MedicamentoList.newBuilder() to construct.
  private MedicamentoList(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private MedicamentoList() {
    resultList_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private MedicamentoList(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
              resultList_ = new java.util.ArrayList<com.tp_sd_1.stubs.medicamento.Medicamento>();
              mutable_bitField0_ |= 0x00000001;
            }
            resultList_.add(
                input.readMessage(com.tp_sd_1.stubs.medicamento.Medicamento.parser(), extensionRegistry));
            break;
          }
          case 18: {
            com.google.protobuf.Int32Value.Builder subBuilder = null;
            if (resultCount_ != null) {
              subBuilder = resultCount_.toBuilder();
            }
            resultCount_ = input.readMessage(com.google.protobuf.Int32Value.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(resultCount_);
              resultCount_ = subBuilder.buildPartial();
            }

            break;
          }
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
        resultList_ = java.util.Collections.unmodifiableList(resultList_);
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.tp_sd_1.stubs.medicamento.MedicamentoOuterClass.internal_static_com_tp_sd_1_stubs_medicamento_MedicamentoList_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.tp_sd_1.stubs.medicamento.MedicamentoOuterClass.internal_static_com_tp_sd_1_stubs_medicamento_MedicamentoList_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.tp_sd_1.stubs.medicamento.MedicamentoList.class, com.tp_sd_1.stubs.medicamento.MedicamentoList.Builder.class);
  }

  private int bitField0_;
  public static final int RESULTLIST_FIELD_NUMBER = 1;
  private java.util.List<com.tp_sd_1.stubs.medicamento.Medicamento> resultList_;
  /**
   * <code>repeated .com.tp_sd_1.stubs.medicamento.Medicamento resultList = 1;</code>
   */
  public java.util.List<com.tp_sd_1.stubs.medicamento.Medicamento> getResultListList() {
    return resultList_;
  }
  /**
   * <code>repeated .com.tp_sd_1.stubs.medicamento.Medicamento resultList = 1;</code>
   */
  public java.util.List<? extends com.tp_sd_1.stubs.medicamento.MedicamentoOrBuilder> 
      getResultListOrBuilderList() {
    return resultList_;
  }
  /**
   * <code>repeated .com.tp_sd_1.stubs.medicamento.Medicamento resultList = 1;</code>
   */
  public int getResultListCount() {
    return resultList_.size();
  }
  /**
   * <code>repeated .com.tp_sd_1.stubs.medicamento.Medicamento resultList = 1;</code>
   */
  public com.tp_sd_1.stubs.medicamento.Medicamento getResultList(int index) {
    return resultList_.get(index);
  }
  /**
   * <code>repeated .com.tp_sd_1.stubs.medicamento.Medicamento resultList = 1;</code>
   */
  public com.tp_sd_1.stubs.medicamento.MedicamentoOrBuilder getResultListOrBuilder(
      int index) {
    return resultList_.get(index);
  }

  public static final int RESULTCOUNT_FIELD_NUMBER = 2;
  private com.google.protobuf.Int32Value resultCount_;
  /**
   * <code>.google.protobuf.Int32Value resultCount = 2;</code>
   */
  public boolean hasResultCount() {
    return resultCount_ != null;
  }
  /**
   * <code>.google.protobuf.Int32Value resultCount = 2;</code>
   */
  public com.google.protobuf.Int32Value getResultCount() {
    return resultCount_ == null ? com.google.protobuf.Int32Value.getDefaultInstance() : resultCount_;
  }
  /**
   * <code>.google.protobuf.Int32Value resultCount = 2;</code>
   */
  public com.google.protobuf.Int32ValueOrBuilder getResultCountOrBuilder() {
    return getResultCount();
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    for (int i = 0; i < resultList_.size(); i++) {
      output.writeMessage(1, resultList_.get(i));
    }
    if (resultCount_ != null) {
      output.writeMessage(2, getResultCount());
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    for (int i = 0; i < resultList_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, resultList_.get(i));
    }
    if (resultCount_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, getResultCount());
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.tp_sd_1.stubs.medicamento.MedicamentoList)) {
      return super.equals(obj);
    }
    com.tp_sd_1.stubs.medicamento.MedicamentoList other = (com.tp_sd_1.stubs.medicamento.MedicamentoList) obj;

    boolean result = true;
    result = result && getResultListList()
        .equals(other.getResultListList());
    result = result && (hasResultCount() == other.hasResultCount());
    if (hasResultCount()) {
      result = result && getResultCount()
          .equals(other.getResultCount());
    }
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getResultListCount() > 0) {
      hash = (37 * hash) + RESULTLIST_FIELD_NUMBER;
      hash = (53 * hash) + getResultListList().hashCode();
    }
    if (hasResultCount()) {
      hash = (37 * hash) + RESULTCOUNT_FIELD_NUMBER;
      hash = (53 * hash) + getResultCount().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.tp_sd_1.stubs.medicamento.MedicamentoList parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.tp_sd_1.stubs.medicamento.MedicamentoList parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.tp_sd_1.stubs.medicamento.MedicamentoList parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.tp_sd_1.stubs.medicamento.MedicamentoList parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.tp_sd_1.stubs.medicamento.MedicamentoList parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.tp_sd_1.stubs.medicamento.MedicamentoList parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.tp_sd_1.stubs.medicamento.MedicamentoList parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.tp_sd_1.stubs.medicamento.MedicamentoList parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.tp_sd_1.stubs.medicamento.MedicamentoList parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.tp_sd_1.stubs.medicamento.MedicamentoList parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.tp_sd_1.stubs.medicamento.MedicamentoList parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.tp_sd_1.stubs.medicamento.MedicamentoList parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.tp_sd_1.stubs.medicamento.MedicamentoList prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code com.tp_sd_1.stubs.medicamento.MedicamentoList}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:com.tp_sd_1.stubs.medicamento.MedicamentoList)
      com.tp_sd_1.stubs.medicamento.MedicamentoListOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.tp_sd_1.stubs.medicamento.MedicamentoOuterClass.internal_static_com_tp_sd_1_stubs_medicamento_MedicamentoList_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.tp_sd_1.stubs.medicamento.MedicamentoOuterClass.internal_static_com_tp_sd_1_stubs_medicamento_MedicamentoList_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.tp_sd_1.stubs.medicamento.MedicamentoList.class, com.tp_sd_1.stubs.medicamento.MedicamentoList.Builder.class);
    }

    // Construct using com.tp_sd_1.stubs.medicamento.MedicamentoList.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getResultListFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      if (resultListBuilder_ == null) {
        resultList_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
      } else {
        resultListBuilder_.clear();
      }
      if (resultCountBuilder_ == null) {
        resultCount_ = null;
      } else {
        resultCount_ = null;
        resultCountBuilder_ = null;
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.tp_sd_1.stubs.medicamento.MedicamentoOuterClass.internal_static_com_tp_sd_1_stubs_medicamento_MedicamentoList_descriptor;
    }

    @java.lang.Override
    public com.tp_sd_1.stubs.medicamento.MedicamentoList getDefaultInstanceForType() {
      return com.tp_sd_1.stubs.medicamento.MedicamentoList.getDefaultInstance();
    }

    @java.lang.Override
    public com.tp_sd_1.stubs.medicamento.MedicamentoList build() {
      com.tp_sd_1.stubs.medicamento.MedicamentoList result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.tp_sd_1.stubs.medicamento.MedicamentoList buildPartial() {
      com.tp_sd_1.stubs.medicamento.MedicamentoList result = new com.tp_sd_1.stubs.medicamento.MedicamentoList(this);
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      if (resultListBuilder_ == null) {
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          resultList_ = java.util.Collections.unmodifiableList(resultList_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.resultList_ = resultList_;
      } else {
        result.resultList_ = resultListBuilder_.build();
      }
      if (resultCountBuilder_ == null) {
        result.resultCount_ = resultCount_;
      } else {
        result.resultCount_ = resultCountBuilder_.build();
      }
      result.bitField0_ = to_bitField0_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return (Builder) super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.tp_sd_1.stubs.medicamento.MedicamentoList) {
        return mergeFrom((com.tp_sd_1.stubs.medicamento.MedicamentoList)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.tp_sd_1.stubs.medicamento.MedicamentoList other) {
      if (other == com.tp_sd_1.stubs.medicamento.MedicamentoList.getDefaultInstance()) return this;
      if (resultListBuilder_ == null) {
        if (!other.resultList_.isEmpty()) {
          if (resultList_.isEmpty()) {
            resultList_ = other.resultList_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureResultListIsMutable();
            resultList_.addAll(other.resultList_);
          }
          onChanged();
        }
      } else {
        if (!other.resultList_.isEmpty()) {
          if (resultListBuilder_.isEmpty()) {
            resultListBuilder_.dispose();
            resultListBuilder_ = null;
            resultList_ = other.resultList_;
            bitField0_ = (bitField0_ & ~0x00000001);
            resultListBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getResultListFieldBuilder() : null;
          } else {
            resultListBuilder_.addAllMessages(other.resultList_);
          }
        }
      }
      if (other.hasResultCount()) {
        mergeResultCount(other.getResultCount());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.tp_sd_1.stubs.medicamento.MedicamentoList parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.tp_sd_1.stubs.medicamento.MedicamentoList) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private java.util.List<com.tp_sd_1.stubs.medicamento.Medicamento> resultList_ =
      java.util.Collections.emptyList();
    private void ensureResultListIsMutable() {
      if (!((bitField0_ & 0x00000001) == 0x00000001)) {
        resultList_ = new java.util.ArrayList<com.tp_sd_1.stubs.medicamento.Medicamento>(resultList_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.tp_sd_1.stubs.medicamento.Medicamento, com.tp_sd_1.stubs.medicamento.Medicamento.Builder, com.tp_sd_1.stubs.medicamento.MedicamentoOrBuilder> resultListBuilder_;

    /**
     * <code>repeated .com.tp_sd_1.stubs.medicamento.Medicamento resultList = 1;</code>
     */
    public java.util.List<com.tp_sd_1.stubs.medicamento.Medicamento> getResultListList() {
      if (resultListBuilder_ == null) {
        return java.util.Collections.unmodifiableList(resultList_);
      } else {
        return resultListBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .com.tp_sd_1.stubs.medicamento.Medicamento resultList = 1;</code>
     */
    public int getResultListCount() {
      if (resultListBuilder_ == null) {
        return resultList_.size();
      } else {
        return resultListBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .com.tp_sd_1.stubs.medicamento.Medicamento resultList = 1;</code>
     */
    public com.tp_sd_1.stubs.medicamento.Medicamento getResultList(int index) {
      if (resultListBuilder_ == null) {
        return resultList_.get(index);
      } else {
        return resultListBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .com.tp_sd_1.stubs.medicamento.Medicamento resultList = 1;</code>
     */
    public Builder setResultList(
        int index, com.tp_sd_1.stubs.medicamento.Medicamento value) {
      if (resultListBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureResultListIsMutable();
        resultList_.set(index, value);
        onChanged();
      } else {
        resultListBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .com.tp_sd_1.stubs.medicamento.Medicamento resultList = 1;</code>
     */
    public Builder setResultList(
        int index, com.tp_sd_1.stubs.medicamento.Medicamento.Builder builderForValue) {
      if (resultListBuilder_ == null) {
        ensureResultListIsMutable();
        resultList_.set(index, builderForValue.build());
        onChanged();
      } else {
        resultListBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .com.tp_sd_1.stubs.medicamento.Medicamento resultList = 1;</code>
     */
    public Builder addResultList(com.tp_sd_1.stubs.medicamento.Medicamento value) {
      if (resultListBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureResultListIsMutable();
        resultList_.add(value);
        onChanged();
      } else {
        resultListBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .com.tp_sd_1.stubs.medicamento.Medicamento resultList = 1;</code>
     */
    public Builder addResultList(
        int index, com.tp_sd_1.stubs.medicamento.Medicamento value) {
      if (resultListBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureResultListIsMutable();
        resultList_.add(index, value);
        onChanged();
      } else {
        resultListBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .com.tp_sd_1.stubs.medicamento.Medicamento resultList = 1;</code>
     */
    public Builder addResultList(
        com.tp_sd_1.stubs.medicamento.Medicamento.Builder builderForValue) {
      if (resultListBuilder_ == null) {
        ensureResultListIsMutable();
        resultList_.add(builderForValue.build());
        onChanged();
      } else {
        resultListBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .com.tp_sd_1.stubs.medicamento.Medicamento resultList = 1;</code>
     */
    public Builder addResultList(
        int index, com.tp_sd_1.stubs.medicamento.Medicamento.Builder builderForValue) {
      if (resultListBuilder_ == null) {
        ensureResultListIsMutable();
        resultList_.add(index, builderForValue.build());
        onChanged();
      } else {
        resultListBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .com.tp_sd_1.stubs.medicamento.Medicamento resultList = 1;</code>
     */
    public Builder addAllResultList(
        java.lang.Iterable<? extends com.tp_sd_1.stubs.medicamento.Medicamento> values) {
      if (resultListBuilder_ == null) {
        ensureResultListIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, resultList_);
        onChanged();
      } else {
        resultListBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .com.tp_sd_1.stubs.medicamento.Medicamento resultList = 1;</code>
     */
    public Builder clearResultList() {
      if (resultListBuilder_ == null) {
        resultList_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        resultListBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .com.tp_sd_1.stubs.medicamento.Medicamento resultList = 1;</code>
     */
    public Builder removeResultList(int index) {
      if (resultListBuilder_ == null) {
        ensureResultListIsMutable();
        resultList_.remove(index);
        onChanged();
      } else {
        resultListBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .com.tp_sd_1.stubs.medicamento.Medicamento resultList = 1;</code>
     */
    public com.tp_sd_1.stubs.medicamento.Medicamento.Builder getResultListBuilder(
        int index) {
      return getResultListFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .com.tp_sd_1.stubs.medicamento.Medicamento resultList = 1;</code>
     */
    public com.tp_sd_1.stubs.medicamento.MedicamentoOrBuilder getResultListOrBuilder(
        int index) {
      if (resultListBuilder_ == null) {
        return resultList_.get(index);  } else {
        return resultListBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .com.tp_sd_1.stubs.medicamento.Medicamento resultList = 1;</code>
     */
    public java.util.List<? extends com.tp_sd_1.stubs.medicamento.MedicamentoOrBuilder> 
         getResultListOrBuilderList() {
      if (resultListBuilder_ != null) {
        return resultListBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(resultList_);
      }
    }
    /**
     * <code>repeated .com.tp_sd_1.stubs.medicamento.Medicamento resultList = 1;</code>
     */
    public com.tp_sd_1.stubs.medicamento.Medicamento.Builder addResultListBuilder() {
      return getResultListFieldBuilder().addBuilder(
          com.tp_sd_1.stubs.medicamento.Medicamento.getDefaultInstance());
    }
    /**
     * <code>repeated .com.tp_sd_1.stubs.medicamento.Medicamento resultList = 1;</code>
     */
    public com.tp_sd_1.stubs.medicamento.Medicamento.Builder addResultListBuilder(
        int index) {
      return getResultListFieldBuilder().addBuilder(
          index, com.tp_sd_1.stubs.medicamento.Medicamento.getDefaultInstance());
    }
    /**
     * <code>repeated .com.tp_sd_1.stubs.medicamento.Medicamento resultList = 1;</code>
     */
    public java.util.List<com.tp_sd_1.stubs.medicamento.Medicamento.Builder> 
         getResultListBuilderList() {
      return getResultListFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.tp_sd_1.stubs.medicamento.Medicamento, com.tp_sd_1.stubs.medicamento.Medicamento.Builder, com.tp_sd_1.stubs.medicamento.MedicamentoOrBuilder> 
        getResultListFieldBuilder() {
      if (resultListBuilder_ == null) {
        resultListBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            com.tp_sd_1.stubs.medicamento.Medicamento, com.tp_sd_1.stubs.medicamento.Medicamento.Builder, com.tp_sd_1.stubs.medicamento.MedicamentoOrBuilder>(
                resultList_,
                ((bitField0_ & 0x00000001) == 0x00000001),
                getParentForChildren(),
                isClean());
        resultList_ = null;
      }
      return resultListBuilder_;
    }

    private com.google.protobuf.Int32Value resultCount_ = null;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.Int32Value, com.google.protobuf.Int32Value.Builder, com.google.protobuf.Int32ValueOrBuilder> resultCountBuilder_;
    /**
     * <code>.google.protobuf.Int32Value resultCount = 2;</code>
     */
    public boolean hasResultCount() {
      return resultCountBuilder_ != null || resultCount_ != null;
    }
    /**
     * <code>.google.protobuf.Int32Value resultCount = 2;</code>
     */
    public com.google.protobuf.Int32Value getResultCount() {
      if (resultCountBuilder_ == null) {
        return resultCount_ == null ? com.google.protobuf.Int32Value.getDefaultInstance() : resultCount_;
      } else {
        return resultCountBuilder_.getMessage();
      }
    }
    /**
     * <code>.google.protobuf.Int32Value resultCount = 2;</code>
     */
    public Builder setResultCount(com.google.protobuf.Int32Value value) {
      if (resultCountBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        resultCount_ = value;
        onChanged();
      } else {
        resultCountBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.google.protobuf.Int32Value resultCount = 2;</code>
     */
    public Builder setResultCount(
        com.google.protobuf.Int32Value.Builder builderForValue) {
      if (resultCountBuilder_ == null) {
        resultCount_ = builderForValue.build();
        onChanged();
      } else {
        resultCountBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.google.protobuf.Int32Value resultCount = 2;</code>
     */
    public Builder mergeResultCount(com.google.protobuf.Int32Value value) {
      if (resultCountBuilder_ == null) {
        if (resultCount_ != null) {
          resultCount_ =
            com.google.protobuf.Int32Value.newBuilder(resultCount_).mergeFrom(value).buildPartial();
        } else {
          resultCount_ = value;
        }
        onChanged();
      } else {
        resultCountBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.google.protobuf.Int32Value resultCount = 2;</code>
     */
    public Builder clearResultCount() {
      if (resultCountBuilder_ == null) {
        resultCount_ = null;
        onChanged();
      } else {
        resultCount_ = null;
        resultCountBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.google.protobuf.Int32Value resultCount = 2;</code>
     */
    public com.google.protobuf.Int32Value.Builder getResultCountBuilder() {
      
      onChanged();
      return getResultCountFieldBuilder().getBuilder();
    }
    /**
     * <code>.google.protobuf.Int32Value resultCount = 2;</code>
     */
    public com.google.protobuf.Int32ValueOrBuilder getResultCountOrBuilder() {
      if (resultCountBuilder_ != null) {
        return resultCountBuilder_.getMessageOrBuilder();
      } else {
        return resultCount_ == null ?
            com.google.protobuf.Int32Value.getDefaultInstance() : resultCount_;
      }
    }
    /**
     * <code>.google.protobuf.Int32Value resultCount = 2;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.Int32Value, com.google.protobuf.Int32Value.Builder, com.google.protobuf.Int32ValueOrBuilder> 
        getResultCountFieldBuilder() {
      if (resultCountBuilder_ == null) {
        resultCountBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.google.protobuf.Int32Value, com.google.protobuf.Int32Value.Builder, com.google.protobuf.Int32ValueOrBuilder>(
                getResultCount(),
                getParentForChildren(),
                isClean());
        resultCount_ = null;
      }
      return resultCountBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:com.tp_sd_1.stubs.medicamento.MedicamentoList)
  }

  // @@protoc_insertion_point(class_scope:com.tp_sd_1.stubs.medicamento.MedicamentoList)
  private static final com.tp_sd_1.stubs.medicamento.MedicamentoList DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.tp_sd_1.stubs.medicamento.MedicamentoList();
  }

  public static com.tp_sd_1.stubs.medicamento.MedicamentoList getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<MedicamentoList>
      PARSER = new com.google.protobuf.AbstractParser<MedicamentoList>() {
    @java.lang.Override
    public MedicamentoList parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new MedicamentoList(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<MedicamentoList> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<MedicamentoList> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.tp_sd_1.stubs.medicamento.MedicamentoList getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

