// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: medicamento.proto

package com.tp_sd_1.stubs.medicamento;

public interface MedicamentoRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.tp_sd_1.stubs.medicamento.MedicamentoRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 id = 1;</code>
   */
  int getId();
}
