// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: medicamento.proto

package com.tp_sd_1.stubs.medicamento;

public interface PaginationOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.tp_sd_1.stubs.medicamento.Pagination)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 page = 1;</code>
   */
  int getPage();

  /**
   * <code>int32 pageSize = 2;</code>
   */
  int getPageSize();

  /**
   * <code>.com.tp_sd_1.stubs.medicamento.Search search = 3;</code>
   */
  boolean hasSearch();
  /**
   * <code>.com.tp_sd_1.stubs.medicamento.Search search = 3;</code>
   */
  com.tp_sd_1.stubs.medicamento.Search getSearch();
  /**
   * <code>.com.tp_sd_1.stubs.medicamento.Search search = 3;</code>
   */
  com.tp_sd_1.stubs.medicamento.SearchOrBuilder getSearchOrBuilder();
}
