// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: medicamento.proto

package com.tp_sd_1.stubs.medicamento;

/**
 * <pre>
 * Para ayudarnos con las queries del listar
 * </pre>
 *
 * Protobuf type {@code com.tp_sd_1.stubs.medicamento.Pagination}
 */
public  final class Pagination extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:com.tp_sd_1.stubs.medicamento.Pagination)
    PaginationOrBuilder {
private static final long serialVersionUID = 0L;
  // Use Pagination.newBuilder() to construct.
  private Pagination(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private Pagination() {
    page_ = 0;
    pageSize_ = 0;
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private Pagination(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 8: {

            page_ = input.readInt32();
            break;
          }
          case 16: {

            pageSize_ = input.readInt32();
            break;
          }
          case 26: {
            com.tp_sd_1.stubs.medicamento.Search.Builder subBuilder = null;
            if (search_ != null) {
              subBuilder = search_.toBuilder();
            }
            search_ = input.readMessage(com.tp_sd_1.stubs.medicamento.Search.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(search_);
              search_ = subBuilder.buildPartial();
            }

            break;
          }
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.tp_sd_1.stubs.medicamento.MedicamentoOuterClass.internal_static_com_tp_sd_1_stubs_medicamento_Pagination_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.tp_sd_1.stubs.medicamento.MedicamentoOuterClass.internal_static_com_tp_sd_1_stubs_medicamento_Pagination_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.tp_sd_1.stubs.medicamento.Pagination.class, com.tp_sd_1.stubs.medicamento.Pagination.Builder.class);
  }

  public static final int PAGE_FIELD_NUMBER = 1;
  private int page_;
  /**
   * <code>int32 page = 1;</code>
   */
  public int getPage() {
    return page_;
  }

  public static final int PAGESIZE_FIELD_NUMBER = 2;
  private int pageSize_;
  /**
   * <code>int32 pageSize = 2;</code>
   */
  public int getPageSize() {
    return pageSize_;
  }

  public static final int SEARCH_FIELD_NUMBER = 3;
  private com.tp_sd_1.stubs.medicamento.Search search_;
  /**
   * <code>.com.tp_sd_1.stubs.medicamento.Search search = 3;</code>
   */
  public boolean hasSearch() {
    return search_ != null;
  }
  /**
   * <code>.com.tp_sd_1.stubs.medicamento.Search search = 3;</code>
   */
  public com.tp_sd_1.stubs.medicamento.Search getSearch() {
    return search_ == null ? com.tp_sd_1.stubs.medicamento.Search.getDefaultInstance() : search_;
  }
  /**
   * <code>.com.tp_sd_1.stubs.medicamento.Search search = 3;</code>
   */
  public com.tp_sd_1.stubs.medicamento.SearchOrBuilder getSearchOrBuilder() {
    return getSearch();
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (page_ != 0) {
      output.writeInt32(1, page_);
    }
    if (pageSize_ != 0) {
      output.writeInt32(2, pageSize_);
    }
    if (search_ != null) {
      output.writeMessage(3, getSearch());
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (page_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(1, page_);
    }
    if (pageSize_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(2, pageSize_);
    }
    if (search_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(3, getSearch());
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.tp_sd_1.stubs.medicamento.Pagination)) {
      return super.equals(obj);
    }
    com.tp_sd_1.stubs.medicamento.Pagination other = (com.tp_sd_1.stubs.medicamento.Pagination) obj;

    boolean result = true;
    result = result && (getPage()
        == other.getPage());
    result = result && (getPageSize()
        == other.getPageSize());
    result = result && (hasSearch() == other.hasSearch());
    if (hasSearch()) {
      result = result && getSearch()
          .equals(other.getSearch());
    }
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + PAGE_FIELD_NUMBER;
    hash = (53 * hash) + getPage();
    hash = (37 * hash) + PAGESIZE_FIELD_NUMBER;
    hash = (53 * hash) + getPageSize();
    if (hasSearch()) {
      hash = (37 * hash) + SEARCH_FIELD_NUMBER;
      hash = (53 * hash) + getSearch().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.tp_sd_1.stubs.medicamento.Pagination parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.tp_sd_1.stubs.medicamento.Pagination parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.tp_sd_1.stubs.medicamento.Pagination parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.tp_sd_1.stubs.medicamento.Pagination parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.tp_sd_1.stubs.medicamento.Pagination parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.tp_sd_1.stubs.medicamento.Pagination parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.tp_sd_1.stubs.medicamento.Pagination parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.tp_sd_1.stubs.medicamento.Pagination parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.tp_sd_1.stubs.medicamento.Pagination parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.tp_sd_1.stubs.medicamento.Pagination parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.tp_sd_1.stubs.medicamento.Pagination parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.tp_sd_1.stubs.medicamento.Pagination parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.tp_sd_1.stubs.medicamento.Pagination prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * Para ayudarnos con las queries del listar
   * </pre>
   *
   * Protobuf type {@code com.tp_sd_1.stubs.medicamento.Pagination}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:com.tp_sd_1.stubs.medicamento.Pagination)
      com.tp_sd_1.stubs.medicamento.PaginationOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.tp_sd_1.stubs.medicamento.MedicamentoOuterClass.internal_static_com_tp_sd_1_stubs_medicamento_Pagination_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.tp_sd_1.stubs.medicamento.MedicamentoOuterClass.internal_static_com_tp_sd_1_stubs_medicamento_Pagination_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.tp_sd_1.stubs.medicamento.Pagination.class, com.tp_sd_1.stubs.medicamento.Pagination.Builder.class);
    }

    // Construct using com.tp_sd_1.stubs.medicamento.Pagination.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      page_ = 0;

      pageSize_ = 0;

      if (searchBuilder_ == null) {
        search_ = null;
      } else {
        search_ = null;
        searchBuilder_ = null;
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.tp_sd_1.stubs.medicamento.MedicamentoOuterClass.internal_static_com_tp_sd_1_stubs_medicamento_Pagination_descriptor;
    }

    @java.lang.Override
    public com.tp_sd_1.stubs.medicamento.Pagination getDefaultInstanceForType() {
      return com.tp_sd_1.stubs.medicamento.Pagination.getDefaultInstance();
    }

    @java.lang.Override
    public com.tp_sd_1.stubs.medicamento.Pagination build() {
      com.tp_sd_1.stubs.medicamento.Pagination result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.tp_sd_1.stubs.medicamento.Pagination buildPartial() {
      com.tp_sd_1.stubs.medicamento.Pagination result = new com.tp_sd_1.stubs.medicamento.Pagination(this);
      result.page_ = page_;
      result.pageSize_ = pageSize_;
      if (searchBuilder_ == null) {
        result.search_ = search_;
      } else {
        result.search_ = searchBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return (Builder) super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.tp_sd_1.stubs.medicamento.Pagination) {
        return mergeFrom((com.tp_sd_1.stubs.medicamento.Pagination)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.tp_sd_1.stubs.medicamento.Pagination other) {
      if (other == com.tp_sd_1.stubs.medicamento.Pagination.getDefaultInstance()) return this;
      if (other.getPage() != 0) {
        setPage(other.getPage());
      }
      if (other.getPageSize() != 0) {
        setPageSize(other.getPageSize());
      }
      if (other.hasSearch()) {
        mergeSearch(other.getSearch());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.tp_sd_1.stubs.medicamento.Pagination parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.tp_sd_1.stubs.medicamento.Pagination) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private int page_ ;
    /**
     * <code>int32 page = 1;</code>
     */
    public int getPage() {
      return page_;
    }
    /**
     * <code>int32 page = 1;</code>
     */
    public Builder setPage(int value) {
      
      page_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 page = 1;</code>
     */
    public Builder clearPage() {
      
      page_ = 0;
      onChanged();
      return this;
    }

    private int pageSize_ ;
    /**
     * <code>int32 pageSize = 2;</code>
     */
    public int getPageSize() {
      return pageSize_;
    }
    /**
     * <code>int32 pageSize = 2;</code>
     */
    public Builder setPageSize(int value) {
      
      pageSize_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 pageSize = 2;</code>
     */
    public Builder clearPageSize() {
      
      pageSize_ = 0;
      onChanged();
      return this;
    }

    private com.tp_sd_1.stubs.medicamento.Search search_ = null;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.tp_sd_1.stubs.medicamento.Search, com.tp_sd_1.stubs.medicamento.Search.Builder, com.tp_sd_1.stubs.medicamento.SearchOrBuilder> searchBuilder_;
    /**
     * <code>.com.tp_sd_1.stubs.medicamento.Search search = 3;</code>
     */
    public boolean hasSearch() {
      return searchBuilder_ != null || search_ != null;
    }
    /**
     * <code>.com.tp_sd_1.stubs.medicamento.Search search = 3;</code>
     */
    public com.tp_sd_1.stubs.medicamento.Search getSearch() {
      if (searchBuilder_ == null) {
        return search_ == null ? com.tp_sd_1.stubs.medicamento.Search.getDefaultInstance() : search_;
      } else {
        return searchBuilder_.getMessage();
      }
    }
    /**
     * <code>.com.tp_sd_1.stubs.medicamento.Search search = 3;</code>
     */
    public Builder setSearch(com.tp_sd_1.stubs.medicamento.Search value) {
      if (searchBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        search_ = value;
        onChanged();
      } else {
        searchBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.com.tp_sd_1.stubs.medicamento.Search search = 3;</code>
     */
    public Builder setSearch(
        com.tp_sd_1.stubs.medicamento.Search.Builder builderForValue) {
      if (searchBuilder_ == null) {
        search_ = builderForValue.build();
        onChanged();
      } else {
        searchBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.com.tp_sd_1.stubs.medicamento.Search search = 3;</code>
     */
    public Builder mergeSearch(com.tp_sd_1.stubs.medicamento.Search value) {
      if (searchBuilder_ == null) {
        if (search_ != null) {
          search_ =
            com.tp_sd_1.stubs.medicamento.Search.newBuilder(search_).mergeFrom(value).buildPartial();
        } else {
          search_ = value;
        }
        onChanged();
      } else {
        searchBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.com.tp_sd_1.stubs.medicamento.Search search = 3;</code>
     */
    public Builder clearSearch() {
      if (searchBuilder_ == null) {
        search_ = null;
        onChanged();
      } else {
        search_ = null;
        searchBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.com.tp_sd_1.stubs.medicamento.Search search = 3;</code>
     */
    public com.tp_sd_1.stubs.medicamento.Search.Builder getSearchBuilder() {
      
      onChanged();
      return getSearchFieldBuilder().getBuilder();
    }
    /**
     * <code>.com.tp_sd_1.stubs.medicamento.Search search = 3;</code>
     */
    public com.tp_sd_1.stubs.medicamento.SearchOrBuilder getSearchOrBuilder() {
      if (searchBuilder_ != null) {
        return searchBuilder_.getMessageOrBuilder();
      } else {
        return search_ == null ?
            com.tp_sd_1.stubs.medicamento.Search.getDefaultInstance() : search_;
      }
    }
    /**
     * <code>.com.tp_sd_1.stubs.medicamento.Search search = 3;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.tp_sd_1.stubs.medicamento.Search, com.tp_sd_1.stubs.medicamento.Search.Builder, com.tp_sd_1.stubs.medicamento.SearchOrBuilder> 
        getSearchFieldBuilder() {
      if (searchBuilder_ == null) {
        searchBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.tp_sd_1.stubs.medicamento.Search, com.tp_sd_1.stubs.medicamento.Search.Builder, com.tp_sd_1.stubs.medicamento.SearchOrBuilder>(
                getSearch(),
                getParentForChildren(),
                isClean());
        search_ = null;
      }
      return searchBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:com.tp_sd_1.stubs.medicamento.Pagination)
  }

  // @@protoc_insertion_point(class_scope:com.tp_sd_1.stubs.medicamento.Pagination)
  private static final com.tp_sd_1.stubs.medicamento.Pagination DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.tp_sd_1.stubs.medicamento.Pagination();
  }

  public static com.tp_sd_1.stubs.medicamento.Pagination getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<Pagination>
      PARSER = new com.google.protobuf.AbstractParser<Pagination>() {
    @java.lang.Override
    public Pagination parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new Pagination(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<Pagination> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<Pagination> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.tp_sd_1.stubs.medicamento.Pagination getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

