// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: medicamento.proto

package com.tp_sd_1.stubs.medicamento;

public interface SearchOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.tp_sd_1.stubs.medicamento.Search)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.google.protobuf.Any filter = 1;</code>
   */
  boolean hasFilter();
  /**
   * <code>.google.protobuf.Any filter = 1;</code>
   */
  com.google.protobuf.Any getFilter();
  /**
   * <code>.google.protobuf.Any filter = 1;</code>
   */
  com.google.protobuf.AnyOrBuilder getFilterOrBuilder();

  /**
   * <code>string jsonFilter = 2;</code>
   */
  java.lang.String getJsonFilter();
  /**
   * <code>string jsonFilter = 2;</code>
   */
  com.google.protobuf.ByteString
      getJsonFilterBytes();
}
