// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: medicamento.proto

package com.tp_sd_1.stubs.medicamento;

public interface TipoMedicamentoOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.tp_sd_1.stubs.medicamento.TipoMedicamento)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 id = 1;</code>
   */
  int getId();

  /**
   * <code>string nombre = 2;</code>
   */
  java.lang.String getNombre();
  /**
   * <code>string nombre = 2;</code>
   */
  com.google.protobuf.ByteString
      getNombreBytes();
}
